#! /bin/sh

### BEGIN INIT INFO
# Provides:          nettrarec
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the netrec
# Description:       starts netrec using start-stop-daemon
### END INIT INFO


DAEMON=netrec
DESC="NetTraRec"

test -x $DAEMON || exit 0

case "$1" in
  start)
        echo "Starting $DESC"
        $DAEMON -pr -kp local
        ;;
  stop)
        echo "Stopping $DESC"
        $DAEMON -t
        ;;
  restart|force-reload)
        echo "Restarting $DESC"
        $DAEMON -t
        $DAEMON
        ;;
  status)
        $DAEMON -v
        ;;
  *)
        echo "Usage: $NAME {start|stop|restart|status}" >&2
        exit 1
        ;;
esac
exit 0